add controllers
KoltsovaIA/java-shareit pull request #1
Opened 2023-06-22 18:21 UTC by KoltsovaIA

2023-06-22 19:10 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе. Просьба добавить валидацию полей и исправить другие мелкие неточности.

2023-06-22 19:10 UTC, Frilock commented on pom.xml
> +        <dependency>
Кажется съехало форматирование, добавление зависимости должно быть в уровень с другими (возможно проблемы с отображением в GitHub)

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +public class ErrorResponse {
Можете воспользоваться возможностями ломбока

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
Какой то не очень понятный класс, а смысл наследоваться и не передавать в super саму ошибку в конструкторе?
Чем данный класс принципиально отличается от других классов исключений?

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
@Autowired можно не писать, поскольку вы бины "инжектите" через конструктор
  
  Кроме того, можете над классом повесить аннотацию от lombok RequiredArgsConstructor или AllArgsConstructor, при применении которых конструктор будет создан не явно

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Integer userId, @RequestBody ItemDto itemDto) {
X-Sharer-User-Id литерал повторяется более 2х раз, вынесите его в константу класса

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemDto.setId(id);
Всю логику из методов нужно перенести в сервисный слой, это конечно дискуссионный момент, и иногда часть логики может быть в контролере, но в данном случае думаю, что будет правильнее всю логику перенести в сервис.
Обычно в контролере располагают только валидацию данных и вызов методов сервиса.

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
Я видел в зависимостях у вас spring-validation, но валидация у вас никак не используется. Вы принципиально не хотите валидировать данные? https://struchkov.dev/blog/ru/spring-boot-validation/

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static Item dtoToItem(ItemDto itemDto) {
Предлагаю для входных параметров itemDto и item добавить аннотацию NonNull, чтобы показать, что данный параметр не может быть null (не может быть передан)

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private final Map<Integer, Item> items = new HashMap<>();
final поля располагаются выше остальных
то есть сначала
static final
потом final
потом другие

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private int id = 0;
Идентификатор может быть статичным, по идее вам должна подсказать это IDEA

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +public class ItemRepositoryImpl implements ItemRepository {
Вообще в качестве совета предлагаю установить плагин sonarlint, это статический анализатор кода, подскажет ряд хороших практик

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (item.getName() == null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +            throw new ItemNotFoundException("Обновить вещь может только её владелец.");
Предложил бы в сообщение об ошибке добавить какую то уникальную информацию, например ид пользователя

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (!StringUtils.isBlank(text)) {
есть функция isNotBlank и не придется инвертировать условие

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                if ((value.getDescription().toLowerCase().contains(text.toLowerCase()) ||
Используйте StringUtils.containsIgnoreCase

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
Лишняя пустая строка

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @Autowired
Лишняя аннотация

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        );
Не на той строке скобка

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userToDto(userService.updateUserById(dtoToUser(userDto))
Сьеъало форматирование

2023-06-22 19:10 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +@Repository
Достаточно одной аннотации Repository

2023-06-26 17:19 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static Item dtoToItem(ItemDto itemDto) {
NotNull быть не может. В тех же тестах приходит, например, одно поле.
Для этого у меня в методах поля проверяются на null. Например в апдейте, если поле пришло пустое, то его оставляем как оно было в изначальном объекте до изменения.

2023-06-26 17:21 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (!StringUtils.isBlank(text)) {
done

2023-06-26 17:21 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +                if ((value.getDescription().toLowerCase().contains(text.toLowerCase()) ||
done

2023-06-26 17:21 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
done

2023-06-26 17:21 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @Autowired
done

2023-06-26 17:21 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        );
done

2023-06-26 17:22 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        return userToDto(userService.updateUserById(dtoToUser(userDto))
done

2023-06-26 17:22 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +@Repository
done

2023-06-26 17:25 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +            throw new ItemNotFoundException("Обновить вещь может только её владелец.");
done

2023-06-26 18:38 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +public class ItemRepositoryImpl implements ItemRepository {
Спасибо
Done

2023-06-26 18:39 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (item.getName() == null) {
Не разобралась почему это будет компактнее.
Ну или не правильно поняла ваш комментарий

2023-06-26 18:43 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private int id = 0;
IDEA не подсказывала
done

2023-06-26 18:55 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
done

2023-06-26 19:02 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Integer userId, @RequestBody ItemDto itemDto) {
done

2023-06-26 19:03 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    private final Map<Integer, Item> items = new HashMap<>();
done

2023-06-26 19:18 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +public class ErrorResponse {
done

2023-06-26 19:28 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/exception/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
done

2023-06-26 19:37 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/exception/IncorrectParameterException.java
> +public class IncorrectParameterException extends RuntimeException {
done

2023-06-26 19:38 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +public class ErrorResponse {
done

2023-06-27 15:43 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
done

2023-06-27 15:43 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static Item dtoToItem(ItemDto itemDto) {
done

2023-06-27 17:48 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        itemDto.setId(id);
Я бы хотела оставить в контроллере.
Если у нас будет не один сервис, а несколько, то в данный момент они будут передавать объекты, а если сделать так как вы предлагаете, то второй сервис будет получать дто и придется для второго сервиса делать так же преобразование.

2023-06-28 19:38 UTC, Frilock approved these changes
Добрый день, работу принимаю, критики нет, но я оставил пару важных комментариев. Ознакомьтесь пожалуйста. Будут вопросы - напишите

2023-06-28 19:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    public static Item dtoToItem(ItemDto itemDto) {
Не вижу, чтоб что то добавилось =(

2023-06-28 19:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    public Item createItem(@Valid Item item) {
Данная аннотация стоит у вас в контролере, ее нет смысла ставить в свое репозиториев, поскольку данные уже будут провалидированы

2023-06-28 19:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +    @Autowired
Вообще "инжектить" бины, правильнее либо через сеттер, либо через конструктор.

2023-06-28 19:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (item.getName() == null) {
Пересмотрел код, мой комментарий был немного некорректный. В данном случае не подойдет, но вообще данная конструкция позволяет вместо 3х строчек if было бы так:
Optiona.ofNullable(oldItem.getName).ifPresent(item::setName); 
Как пример на будущее

2023-06-28 19:38 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    public User createUser(@Valid User user) {
Лишняя аннотация

2023-07-03 08:26 UTC, merged