add bookings
KoltsovaIA/java-shareit pull request #2
Opened 2023-07-15 11:25 UTC by KoltsovaIA

2023-07-15 17:52 UTC, Frilock requested changes
Добрый день, оставил часть комментариев к работе.

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @PatchMapping({"/{bookingId}"})
Лишние {}

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public OutgoingBookingDto getBookingByUserId(@Valid @NotNull @RequestHeader(USER_ID_HEADER) Long userId,
А зачем тут @Valid?

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (state == null) {
Всю эту логику нужно перенести в сервис. Мы по моему с вами как раз это обсуждали, теперь у вас в контролере куча логики, что не верно

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +        return OutgoingBookingDto.builder()
А зачем в ДТО хранить целый обьект booker? по идее достаточно будет хранить только идентификатор итема и читателя. Тогда Вам не придется тут делать лишние запросы
Так получается что вы раздуваете обьект

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +
Лишняя пустая строка

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!itemService.itemIsExistsById(itemId)) {
Предлагаю всю эту кучу проверок вынести в приватный метод валидации

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
Над частью методов отсутствуют транзакции

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!userService.userIsExistsById(bookerId)) {
Код проверки повторяется много раз, тоже можно вынести в отдельный метод

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public OutgoingCommentDto createComment(@Valid @RequestHeader(USER_ID_HEADER) Long userId,
Лишние аннотации Valid, посмотрите как аннотация работает

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler"})
А это для чего вам?

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler"})
Зачем вам эта аннотация в классе моделей?

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +@Repository
Лишняя аннотация

2023-07-15 17:52 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +//        if (userRepository.existsByEmail(user.getEmail())){
Закоментированный код нужно убрать

2023-07-15 17:52 UTC, Frilock commented on src/main/resources/schema.sql
> +    user_email    varchar(100) NOT NULL UNIQUE,
Размерность полей которую вы указываете тут, добавьте так же в аннотации Column классов моделей, в признаке lenght, чтобы не приходилось в случае чего лазить в БД для уточнения размерности полей

2023-07-16 14:56 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @PatchMapping({"/{bookingId}"})
done

2023-07-16 15:00 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public OutgoingBookingDto getBookingByUserId(@Valid @NotNull @RequestHeader(USER_ID_HEADER) Long userId,
done

2023-07-16 15:09 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +//        if (userRepository.existsByEmail(user.getEmail())){
done

2023-07-16 15:10 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +
done

2023-07-16 15:20 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public OutgoingCommentDto createComment(@Valid @RequestHeader(USER_ID_HEADER) Long userId,
done

2023-07-16 15:27 UTC, KoltsovaIA commented on src/main/resources/schema.sql
> +    user_email    varchar(100) NOT NULL UNIQUE,
done

2023-07-16 15:35 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Repository
done

2023-07-16 15:45 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +        return OutgoingBookingDto.builder()
`pm.test("Test booking 'booker.id' field", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData).to.have.property('booker');
    pm.expect(jsonData.booker).to.have.property('id');
    pm.expect(jsonData.booker.id, '"booker.id"  must be "1"').to.eql(1);
});
pm.test("Test booking 'item.id' field", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData).to.have.property('item');
    pm.expect(jsonData.item).to.have.property('id');
    pm.expect(jsonData.item.id, '"item.id"  must be "2"').to.eql(2);
});
pm.test("Test booking 'item.name' field", function () {
    var jsonData = pm.response.json();
    pm.expect(jsonData).to.have.property('item');
    pm.expect(jsonData.item).to.have.property('name');
    pm.expect(jsonData.item.name, '"item.name"  must be "Отвертка"').to.eql('Отвертка');
});`

Тут либо цеплять сами объекты, либо наворачивать ДТО для ДТО. Я это поняла так

2023-07-16 15:58 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!userService.userIsExistsById(bookerId)) {
done

2023-07-16 15:58 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +@Repository
done

2023-07-16 16:01 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!itemService.itemIsExistsById(itemId)) {
Эти проверки используются только в методе createBooking, есть ли смысл в преждевременной оптимизации, кроме как спрятать код?

2023-07-16 17:00 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +public class BookingServiceImpl implements BookingService {
done

2023-07-16 17:05 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler"})
https://stackoverflow.com/a/67354659 это не совсем то что я прочла в первый раз, но пояснение хорошее
что-то ничего в голову не пришло как избавиться от вот такого поведения
```
    "item": {
        "id": 2,
        "name": "Отвертка",
        "description": "Аккумуляторная отвертка",
        "available": true,
        "owner": 4,
        "hibernateLazyInitializer"
    }
```
дто выглядит так

```
    public OutgoingBookingDto bookingToDto(Booking booking) {
        return OutgoingBookingDto.builder()
                .id(booking.getId())
                .booker(userService.getUserById(booking.getBookerId()))
                .item(itemService.getItemById(booking.getItemId()))
                .status(booking.getApproved())
                .start(booking.getStart())
                .end(booking.getEnd())
                .build();
    }
```

2023-07-16 17:06 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler"})
ответ в предыдущем обсуждении

2023-07-16 18:28 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (state == null) {
done

2023-07-17 05:22 UTC, Frilock approved these changes
Добрый день, просили не жестить, поэтому работу принимаю, хотя часть моментов с lazyInitializer не очень. Давайте тогда к следующей работе попробуем от нее избавиться. Возможное решение в комментарии написал.

2023-07-17 05:22 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +@Transactional
На самом деле не все так просто, над частью методов нужно ставить readOnly транзакции

2023-07-17 05:22 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +        return OutgoingBookingDto.builder()
Вообще можно сделать ShortDto да. Просто что мне не нравится, так это использование в мапперах других сервисов. По идее маппер должен из ДТО сложить все в ентити и наоборот. Хотя такой вариант тоже допустим

2023-07-17 05:22 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler"})
Возможно это из за того, что в ваших ентити нет связей по типу:
@ManyToOne(optional = false)
	@JoinColumn(name = "owner_id", nullable = false)
	private User owner;

2023-07-17 18:23 UTC, merged