Add item requests
KoltsovaIA/java-shareit pull request #4
Opened 2023-09-01 07:10 UTC by KoltsovaIA

2023-09-01 11:20 UTC, Frilock requested changes
Добрый день, комментарии в коде

2023-09-01 11:20 UTC, Frilock commented on pom.xml
> +            <version>2.5</version>
Версии библиотек нужно вынести в properties

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                           @PositiveOrZero Short from,
Нужно добавить Validated на класс, иначе валидация такая работать не будет

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
>  public class BookingMapper {
Вообще в данном случае маппер свою функцию не выполняет, он должен преобразовывать один обьект в другой, на деле же тут у вас добавлена дополнительная логика. Я бы советовал вычислять нужные атрибуты в сервисах и уже готовые их передавать сюда

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBooker.java
> +    Long id;
Модификатор отуствтует

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBooker.java
> +public class ShortBooker {
Такие обьекты принято называть DTO, добавьте это к названию класса, иначе это может путать

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBooking.java
> +    Long id;
Модификаторы

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/ShortItem.java
> +    Long id;
Модификаторы

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    LinkedList<Booking> getAllByBookerId(Long bookerId, Pageable page);
По моему мы с вами это уже обсуждали, еще в 4й работе - правильно указывать в типе значения интерфейс, а не реализацию, то есть не LinkedList, а List, но вообще поскольку вы работаете в этих методах с обьектом Pageable, то правильнее будет возвращать не лист, а Page

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>              throw new ItemNotFoundException("");
Зачем бросать исключение с пустым описание???

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>              throw new UserNotFoundException("");
Тут тоже

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @Column(name = "description", nullable = false)
В аннотации column также лучше указывать размерность полей которую вы задаете в скриптах, чтобы лишний раз в них не лазить

2023-09-01 11:20 UTC, Frilock commented on src/main/java/ru/practicum/shareit/util/OffsetBasedPageRequest.java
> +public class OffsetBasedPageRequest implements Pageable, Serializable {
А зачем вам такая реализация?) Вам по сути нужно просто 1 параметр на другой поделить и сделать Pageable.of =)

2023-09-01 11:20 UTC, Frilock commented on src/test/java/ru/practicum/shareit/ItemTest/ItemIntegrationTest.java
> +        userService.createUser(user);
Вообще если вы с обьектом работаете, обновляете его и тд, лучше не с глобальным работать, а в тесте конкретный создать и с ним работать

2023-09-02 11:36 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                           @PositiveOrZero Short from,
done

2023-09-02 11:37 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBooker.java
> +    Long id;
done

2023-09-02 11:40 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBooker.java
> +public class ShortBooker {
done

2023-09-02 11:41 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/dto/ShortBooking.java
> +    Long id;
done

2023-09-02 11:41 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/dto/ShortItem.java
> +    Long id;
done

2023-09-02 11:47 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @Column(name = "description", nullable = false)
done

2023-09-02 11:59 UTC, KoltsovaIA commented on pom.xml
> +            <version>2.5</version>
done

2023-09-02 12:06 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>              throw new ItemNotFoundException("");
done

2023-09-02 12:06 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>              throw new UserNotFoundException("");
done

2023-09-02 12:15 UTC, KoltsovaIA commented on src/test/java/ru/practicum/shareit/ItemTest/ItemIntegrationTest.java
> +        userService.createUser(user);
Мысль поняла, для примера параллельно прогоняемые тесты могут быть сломаны модификацией объекта.
Применительно к этому интеграционному тесту, тут объекты не модифицируются, надо ли переделывать?

2023-09-02 12:19 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/util/OffsetBasedPageRequest.java
> +public class OffsetBasedPageRequest implements Pageable, Serializable {
Эта реализация "честно взята" с СО. там же шло обсуждение об ошибках которые могут возникать при подходе предложенном вами, а так же там же шло обсуждение о включение этой реализации в либы.

2023-09-03 07:44 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    LinkedList<Booking> getAllByBookerId(Long bookerId, Pageable page);
Переделала на List.
При переделке на Page, возникла сложность, репозиторий вместо пустого Page, бросает нул поинтер. Пока не нашла хорошего корректного решения. В документации указано что результат работы пагинации корректно использовать и как пэйдж и как лист. Решила остановится на последнем

2023-09-03 07:49 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
>  public class BookingMapper {
Собственно это уже и есть сервис, который занимается исключительно маппингом объектов, да такой переусложненный вариант привычного маппинга. Но в то же время позволяет отделить представления дто от объектов и не перегружать круд сервисы.

2023-09-03 09:27 UTC, TyutterinYakov reviewed
Добрый день! В целом - хорошо) Отметил то, что остается подправить :) Хорошего дня! Если возникнут вопросы - пиши в пачку, буду рад помочь🌅

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                           @RequestParam(required = false) String state,
Почему бы не произвести установку стандартного значения стейта с помощью `defaultValue = "ALL"`, чтобы затем не производить проверки в коде)

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                          @RequestParam(required = false) String state,
Почему бы не произвести установку стандартного значения стейта с помощью `defaultValue = "ALL"`, чтобы затем не производить проверки в коде)

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/OutgoingBookingDto.java
Действительно ли в этом классе требуются аннотации валидации?) Если я не ошибаюсь, то он выступает только в качестве возвращаемого значения, и оно никак не валидируется

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
>  public class BookingMapper {
При текущей реализации нарушается принцип единственной ответственности) Маппер должен заниматься лишь преобразованиями, он не должен знать о слое бизнес-логики, а также его методы не должны быть транзакционными) Следует исключить поля с сервисами, а в методы маппера передавать уже те объекты, что требуются для формирования DTO/модели)

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
Перед с использованием аннотаций для автоматической генерации кода в классах-сущностях - хорошо было бы ознакомиться со статьей)
https://habr.com/ru/company/haulmont/blog/564682/

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
В класс следует добавить логирование) Для этого достаточно использовать аннотацию из lombok ->> `@Slf4j`. Далее в каждый наш хендлер следует добавить логирование сообщения об ошибке)
Также хорошо было бы передать в лог сообщение об ошибке, а можно и весь трейс, чтобы в случае ошибки было проще разобраться, что именно произошло)
Кстати, при логгировании более эффективно использовать не конкатенацию, а заполнитель - placeholder `{}`
Например:
`log.debug("Получен статус 404 Not found {}", ex.getMessage(), ex);`

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      @PostMapping
Аннотация `@NotNull` не имеет смысла, так как заголовок запроса является обязательным, так как в `@RequestHeader` не указано обратное - `defaultValue = ".."` или `required = false`
Аналогично в других местах и не только с `@RequestHeader`

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
>  public class ItemMapper {
Аналогично, маппер никак не должен взаимодействовать с уровнем бизнес-логики)

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/OutgoingCommentDto.java
>  public class OutgoingCommentDto {
Действительно ли в этом классе требуются аннотации валидации?) Если я не ошибаюсь, то он выступает только в качестве возвращаемого значения, и оно никак не валидируется

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/IncomingCommentDto.java
Хорошо было бы исключить лишние поля, чтобы передавать и работать лишь с теми данными, что требуются) Так как при создании требуется лишь поле `text`
Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
Хорошо было бы разбить класс-DTO на несколько, так как, например, при создании нам требуются лишь поля с описанием, названием и доступностью) Остальные же не требуются. То есть один класс будет использоваться для представления тела запроса, а другой - для представления тела ответа) Таким образом мы будем работать только с теми значениями, что требуются в определенной ситуации

Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`. Эта аннотация удобна тем, что допускает null, за счет чего при обновлении по значению мы сможем понять, было передано значение или нет)
Но потребуется для обновления ввести отдельный класс, либо же использовать валидацию по группам
https://struchkov.dev/blog/ru/spring-boot-validation/
Так как при обновлении требуется учитывать лишь `@Size`

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/ShortItemDto.java
Действительно ли в этом классе требуются аннотации валидации?) Если я не ошибаюсь, то он выступает только в качестве возвращаемого значения, и оно никак не валидируется

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
Перед с использованием аннотаций для автоматической генерации кода в классах-сущностях - хорошо было бы ознакомиться со статьей)
https://habr.com/ru/company/haulmont/blog/564682/

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
Перед с использованием аннотаций для автоматической генерации кода в классах-сущностях - хорошо было бы ознакомиться со статьей)
https://habr.com/ru/company/haulmont/blog/564682/

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    private static final String USER_ID_HEADER = "X-Sharer-User-Id";
Хорошо было бы для подобных констант ввести отдельный класс, чтобы не дублировать их во всех классах, где они требуются

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                            @RequestParam(defaultValue = "0", required = false)
Если указано `defaultValue`, это уже подразумевает, что параметр не является обязательным, следовательно `required = false` не требуется)

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/dto/OutgoingItemRequestDto.java
Действительно ли в этом классе требуются аннотации валидации?) Если я не ошибаюсь, то он выступает только в качестве возвращаемого значения, и оно никак не валидируется

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/dto/RequestMapper.java
> +    private final ItemService itemService;
Аналогично, взаимодействие с уровнем бизнес логики следует исключить) Как и аннотацию `@Transactional`

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Data
Перед с использованием аннотаций для автоматической генерации кода в классах-сущностях - хорошо было бы ознакомиться со статьей)
https://habr.com/ru/company/haulmont/blog/564682/

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
>      private final UserService userService;
Аналогично) Взаимодействие с сервисом следует исключить

2023-09-03 09:27 UTC, TyutterinYakov commented on src/test/java/ru/practicum/shareit/ItemTest/ItemControllerTest.java
> +    public static final String USER_ID_HEADER = "X-Sharer-User-Id";
Для этого значения у нас теперь будет введен отдельный класс) Хорошо было бы брать значение из него, чтобы в случае изменений - потребовалось ввести их в одном лишь месте)

2023-09-03 09:27 UTC, TyutterinYakov commented on src/test/java/ru/practicum/shareit/userTest/UserControllerTest.java
Хорошо было бы добавить тест на проверку того, что в случае, если на обновление будет передан пользователь с некорректным форматом почты - возникнет ошибка) 

Если все закончится хорошо, тогда необходимо в `UserDto` использовать валидацию по группам:
Для имени:
`@NotBlank(groups = {Create.class})`
Для почты аннотацию `@Email` следует учитываться для обновления и создания, так как, если она не будет передана вообще, то все будет окей, а если будет, тогда она будет проверена на соответствие почте, а вот аннотацию
`@NotEmpty` только для создания) Так как при обновлении передавать ее не обязательно)
Хорошо было бы ограничить размеры текстовых полей на основе тех ограничений, которые установлены на уровне таблицы в БД, чтобы заранее откинуть некорректные запросы) Для ограничения количества символов можно использовать `@Size`. Эта аннотация удобна тем, что допускает null, за счет чего при обновлении по значению мы сможем понять, было передано значение или нет)

Для методов контроллера пользователя(обновление/создание):
Вместо `@Valid` можно использовать такую аннотацию `@Validated(Create.class)`. Таким образом мы указываем, какую группу аннотаций следует учитывать. `Create` - это интерфейс, который ты создаешь самостоятельно, он будет пустым и служит лишь для указания группы) Аналогично следует поступить при обновлении, но там будет аннотация `@Validated(Update.class)`

Если не использовать валидацию по группам, тогда потребуется при обновлении дополнительно проверять формат переданной строки с почтой в коде, что не очень удобно. Либо же потребуется ввести отдельный класс DTO для обновления, чтобы над полем с почтой использовать `@Email`

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          if (booking.getEnd().isBefore(booking.getStart())) {
(предложение)Эту валидацию можно было бы реализовать с помощью аннотации валидации над классом, чтобы поддерживать декларативный подход https://devcolibri.com/spring-mvc-кастомная-аннотация-для-валидации/
Кстати, если будет интересно то, как реализовать кастомную аннотацию валидации на уровне класса `BookingInputDto` - можешь чекнуть тут) https://github.com/TyutterinYakov/CustomValidationClassLevel Я написал небольшой примерчик, чтобы было проще разобраться в теме)

2023-09-03 09:27 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          if (booking.getEnd().isBefore(booking.getStart())) {
Также можно было бы исключить проверки дат с текущим временем и использовать более декларативный подход:
Например, над start - `@FutureOrPresent`, так как дата начала бронирования может быть равна текущей, либо же быть из будущего. Не забываем о `@NotNull`, так как первая аннотация допускает null)
Аналогично для даты окончания, но в этом случае следует использовать `@Future`, так как дата окончания должна быть после начала бронирования и не может быть ей равна.

2023-09-04 15:18 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>      @PostMapping
done

2023-09-04 15:24 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                            @RequestParam(defaultValue = "0", required = false)
done

2023-09-04 15:36 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/dto/OutgoingBookingDto.java
done

2023-09-04 15:39 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/dto/OutgoingCommentDto.java
>  public class OutgoingCommentDto {
done

2023-09-04 15:41 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/dto/ShortItemDto.java
done

2023-09-04 15:42 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/request/dto/OutgoingItemRequestDto.java
done

2023-09-05 06:03 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                           @RequestParam(required = false) String state,
done

2023-09-05 06:04 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                          @RequestParam(required = false) String state,
done

2023-09-05 17:50 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          if (booking.getEnd().isBefore(booking.getStart())) {
done

2023-09-05 17:51 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
>          if (booking.getEnd().isBefore(booking.getStart())) {
done

2023-09-06 05:49 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    private static final String USER_ID_HEADER = "X-Sharer-User-Id";
done

2023-09-06 05:50 UTC, KoltsovaIA commented on src/test/java/ru/practicum/shareit/ItemTest/ItemControllerTest.java
> +    public static final String USER_ID_HEADER = "X-Sharer-User-Id";
done

2023-09-07 07:46 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
done

2023-09-07 07:47 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
done

2023-09-07 07:47 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/model/Item.java
done

2023-09-07 07:47 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Data
done

2023-09-10 08:37 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
>  public class BookingMapper {
done

2023-09-10 11:40 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
>  public class ItemMapper {
done

2023-09-10 12:57 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/request/dto/RequestMapper.java
> +    private final ItemService itemService;
done

2023-09-10 12:58 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/dto/IncomingCommentDto.java
done

2023-09-10 13:14 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
>      private final UserService userService;
Done

2023-10-04 08:32 UTC, KoltsovaIA commented on src/test/java/ru/practicum/shareit/userTest/UserControllerTest.java
done

2023-10-04 08:54 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
done

2023-10-08 08:57 UTC, KoltsovaIA commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
done

2023-10-10 16:13 UTC, TyutterinYakov approved these changes
Добрый вечер! Поздравляю с успешной сдачей спринта :) Желаю успехов в дальнейшем обучении и покорении новых вершин! Прекрасного вечера и отличного настроения🌃🎇

2023-10-25 16:42 UTC, merged